myproject/myproject/urls.py
"""
URL configuration for myproject project.

The `urlpatterns` list routes URLs to views. For more information, please refer to the Django documentation:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/

Examples:
Function views:
    1. Add an import: from my_app import views
    2. Add a URL to urlpatterns: path('', views.home, name='home')

Class-based views:
    1. Add an import: from other_app.views import Home
    2. Add a URL to urlpatterns: path('', Home.as_view(), name='home')

Including another URLconf:
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns: path('blog/', include('blog.urls'))
"""

# Import necessary Django modules and views
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    # URL pattern to serve media files in development (e.g., uploaded user files)
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    
    # URL pattern to serve static files in development (e.g., CSS, JS)
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    
    # Django admin interface
    path('admin/', admin.site.urls),

    # Homepage route, maps to the homepage view
    path('', views.homepage),

    # About page route, maps to the about page view
    path('about/', views.aboutpage),

    # Include URLs from the 'posts' app
    path('posts/', include('posts.urls')),

    # Include URLs from the 'users' app
    path('users/', include('users.urls')),
]

# Uncomment the next line for serving media files in development (for development only)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.posts_list, name="posts"),
    path('new-post/', views.posts_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_user,name="register"),
    path('login/',views.login_user,name="login"),
    path('logout/',views.logout_user,name="logout"),
]

myproject/templates/about.html
{% extends 'layout.html' %}
{% block title %}
    About
{% endblock %}
{% block content %}
    <h1>About page</h1>
    <p> Check out <a href="/">Home</a> page.</p>
{% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}
{% block title %}
    Home
{% endblock %}
{% block content %}
    <h1>Home page</h1>
    <p> Check out <a href="/about">About</a> page.</p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <nav>
        <a href="/">Home</a> |
        <a href="/about">About</a> |
        <a href="{% url 'posts:posts' %}">News</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">New post</a> |
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-submit">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'users:login' %}">Login</a> |
            <a href="{% url 'users:register' %}">Register</a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>