myproject/myproject/urls.py
"""
URL configuration for myproject project.

The `urlpatterns` list routes URLs to views. For more information, please refer to the Django documentation:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/

Examples:
Function views:
    1. Add an import: from my_app import views
    2. Add a URL to urlpatterns: path('', views.home, name='home')

Class-based views:
    1. Add an import: from other_app.views import Home
    2. Add a URL to urlpatterns: path('', Home.as_view(), name='home')

Including another URLconf:
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns: path('blog/', include('blog.urls'))
"""

# Import necessary Django modules and views
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    # URL pattern to serve media files in development (e.g., uploaded user files)
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    
    # URL pattern to serve static files in development (e.g., CSS, JS)
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    
    # Django admin interface
    path('admin/', admin.site.urls),

    # Homepage route, maps to the homepage view
    path('', views.homepage),

    # About page route, maps to the about page view
    path('about/', views.aboutpage),

    # Include URLs from the 'posts' app
    path('posts/', include('posts.urls')),

    # Include URLs from the 'users' app
    path('users/', include('users.urls')),
]

# Uncomment the next line for serving media files in development (for development only)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.posts_list, name="posts"),
    path('new-post/', views.posts_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField(unique=True, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title
    

myproject/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','slug','banner']
    

myproject/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def posts_list(request):
    """
    View to display the list of all posts.

    This view retrieves all posts from the database, orders them by date 
    in descending order, and renders the 'posts_list.html' template 
    to display the list of posts.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The rendered posts list template with posts.
    """
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    """
    View to display a single post page.

    This view retrieves a single post based on the given slug 
    and renders the 'post_page.html' template to display the post's content.

    Args:
        request (HttpRequest): The HTTP request object.
        slug (str): The slug of the post to retrieve.

    Returns:
        HttpResponse: The rendered post page template with the post.
    """
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url="/users/login/")
def posts_new(request):
    """
    View to create a new post.

    This view displays a form to create a new post. The user must be logged in 
    to access this view. Upon successful form submission, the post is saved 
    with the current user as the author, and the user is redirected to the 
    posts list page.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The rendered new post form template or a redirect to the posts list.
    """
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user  # Assigning the logged-in user as the author
            newpost.save()
            return redirect('posts:posts')  # Redirect to the posts list page
    else:
        form = forms.CreatePost()

    return render(request, 'posts/new_post.html', {'form': form})

myproject/posts/templates/posts/new_post.html
{% extends 'layout.html' %}
{% block title %}
    New post
{% endblock %}
{%block content %}
    <section>
        <h1>New post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit"> Add post</button>
        </form>
    </section>
{% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{%block content %}
    <section>
        <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}"/>
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% block title %}
    Posts
{% endblock %}
{%block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts %}
            <article>
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.date }} by {{post.author}}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor%}
    </section>
{% endblock %}